#!/bin/sh

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

msg='pwned'
vec="${GIT_LANDMINE_VECTOR-}"
if [ -n "$vec" ]
then
	msg="$msg via $vec"
else
    while [ $# -gt 0 ]
    do
        if [ "$1" = '--verify' ]
        then
            msg="$msg via gpg.program"
            break
        fi
        shift
    done
    if [ -n "${msg##* *}" ]
    then
        case $0 in
            .git/hooks/*|hooks/*)
                msg="msg via $0";;
        esac
    fi
fi
exec cowsay "$msg" >/dev/tty

# vim:ts=4 sts=4 sw=4 et
